RSpecDescribeClass:
  Description: 'Check that the first argument to the top level describe is the tested class or module.'
  Enabled: true

RSpecDescribedClass:
  Description: 'Use `described_class` for tested class / module'
  Enabled: true

RSpecDescribeMethod:
  Description: 'Checks that the second argument to top level describe is the tested method name.'
  Enabled: true

RSpecExampleWording:
  Description: 'Do not use should when describing your tests.'
  Enabled: true

RSpecMultipleDescribes:
  Description: 'Checks for multiple top level describes.'
  Enabled: true

RSpecFileName:
  Description: 'Checks the file and folder naming of the spec file.'
  Enabled: true
